### PR TITLE
`fei()` doesn't work with table or matrix?

### LINKED ISSUE #566: Give more informative error message for invalid table inputs to `fei()`
Is this expected?

``` r
library(effectsize)
(Titanic_xtab <- as.table(apply(Titanic, c(2, 4), sum)))
#>         Survived
#> Sex        No  Yes
#>   Male   1364  367
#>   Female  126  344

fei(Titanic_xtab)
#> Error in f(x = model$observed, ...): could not find function "f"

fei(as.matrix(Titanic_xtab))
#> Error in f(x = model$observed, ...): could not find function "f"
```

<sup>Created on 2023-03-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by strengejacke**
Fixes #566

### CODE REVIEW

**Comment by strengejacke** [comment]
hm...

``` r
library(effectsize)
(Titanic_xtab <- as.table(apply(Titanic, c(2, 4), sum)))
#>         Survived
#> Sex        No  Yes
#>   Male   1364  367
#>   Female  126  344

fei(Titanic_xtab)
#> Error: Fei is only applicable to goodness of fit tests.
```

Maybe we should add this warning/error earlier?

**Comment by strengejacke** [comment]
Or we just merge this PR, because it gives a more informative error message than the current behaviour.

**Comment by strengejacke** [comment]
I have revised the function, it now checks for 1D table inputs.

File: R/xtab_corr.R [hunk 1]
```diff
@@ -181,16 +181,20 @@ fei <- function(x, p = rep(1, length(x)),
...
+  if (inherits(x, "BFBayesFactor")) {
     insight::format_error("Fei is only applicable to goodness of fit tests.")
   } else if (!.is_htest_of_type(x, "Chi-squared test for given probabilities", "Chi-squared-test")) {
     x <- suppressWarnings(stats::chisq.test(x, y = NULL, p = p, rescale.p = TRUE))
     x$data.name <- NULL
+
+    table_dim <- dim(x$observed)
+    is_1d_table <- is.null(table_dim) ||            # vector
+      length(table_dim) == 1 ||                     # 1D table
+      (length(table_dim) == 2 && table_dim[2] == 1)
```
Comment (strengejacke) [inline R/xtab_corr.R:194]: I was just wondering, is it possible to have a 1D table with dim 1, 100 or similar? I.e. 1 in the first place? Then we should probably change `(length(table_dim) == 2 && table_dim[2] == 1)` to `(length(table_dim) == 2 && any(table_dim == 1))`
